#Kart over skulen versjon 1. Ingen effektiv kode :)
import turtle
import time

screen = turtle.Screen()
screen.setup(width = 1.0, height = 1.0)
  #fjerne max min og x:
canvas = screen.getcanvas()
root = canvas.winfo_toplevel()
root.overrideredirect(1)

turtle.up()
turtle.right(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(200)
turtle.down()
turtle.pensize(4)
turtle.forward(250)
turtle.left(90)
turtle.forward(500)
turtle.left(90)
turtle.forward(250)
turtle.left(90)
turtle.forward(500)
turtle.up()
turtle.left(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(250)
turtle.write("Teoribygg",font=("Arial", 14, "normal"))

turtle.up()
turtle.forward(200)
turtle.left(90)
turtle.forward(150)
turtle.down()
turtle.forward(80)
turtle.right(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(350)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(430)
turtle.left(90)
turtle.forward(120)
turtle.up()
turtle.left(90)
turtle.forward(280)
turtle.write("Verkstadbygg 1",font=("Arial", 14, "normal"))
turtle.forward(150)

turtle.left(90)
turtle.forward(200)
turtle.down()
turtle.forward(200)
turtle.left(90)
turtle.forward(430)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(430)
turtle.left(90)
turtle.up()
turtle.forward(100)
turtle.left(90)
turtle.forward(150)
turtle.write("Verkstadbygg 2",font=("Arial", 14, "normal"))

turtle.right(180)
turtle.forward(300)
turtle.down()
turtle.forward(200)
turtle.left(90)
turtle.forward(400)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(400)
turtle.up()
turtle.left(180)
turtle.forward(150)
turtle.right(90)
turtle.forward(130)
turtle.write("Hall 3",font=("Arial", 14, "normal"))
#turtle.hideturtle()

turtle.left(180)
turtle.forward(165)
turtle.write("Velkomen til...",font=("Arial", 14, "normal"))
time.sleep(2)
turtle.right(90)
turtle.forward(150)
turtle.write("Stord vidaregåande skule, avd. Vabakkjen",font=("Arial", 30, "normal"))
time.sleep(1)
turtle.bgcolor("Yellow")
time.sleep(0.3)
turtle.bgcolor("Pink")
time.sleep(0.3)
turtle.bgcolor("Yellow")
time.sleep(0.3)
turtle.bgcolor("Pink")
time.sleep(0.2)
turtle.bgcolor("Yellow")
time.sleep(0.3)
turtle.bgcolor("Pink")
time.sleep(0.3)
turtle.bgcolor("Yellow")
time.sleep(0.3)
turtle.bgcolor("Pink")
time.sleep(0.2)
turtle.bgcolor("Yellow")
time.sleep(0.3)
turtle.bgcolor("Pink")
time.sleep(0.3)
turtle.bgcolor("Yellow")
time.sleep(0.3)
turtle.bgcolor("Pink")
time.sleep(0.2)
turtle.bgcolor("White")
turtle.forward(100)
turtle.write("Klikk kvar som helst for å avslutta",font=("Arial", 14, "normal"))
turtle.exitonclick()
turtle.clear






